generic-service:
  nameOverride: hmpps-visit-allocation-api
  serviceAccountName: visit-someone-in-prison
  productId: "DPS035"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-visit-allocation-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-visit-allocation-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /visits/allocation/job/start {
          deny all;
          return 401;
        }
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-visit-allocation-api:
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    visit-allocation-rds:
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
    application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-prison-visits-allocation-events-secret:
      HMPPS_SQS_QUEUES_PRISONVISITSALLOCATIONEVENTS_QUEUE_NAME: "sqs_queue_name"
    sqs-hmpps-prison-visits-allocation-events-dlq-secret:
      HMPPS_SQS_QUEUES_PRISONVISITSALLOCATIONEVENTS_DLQ_NAME: "sqs_queue_name"
    sqs-prison-visits-allocation-processing-job-secret:
      HMPPS_SQS_QUEUES_VISITSALLOCATIONEVENTJOB_QUEUE_NAME: "sqs_queue_name"
    sqs-hmpps-prison-visits-allocation-processing-job-dlq-secret:
      HMPPS_SQS_QUEUES_VISITSALLOCATIONEVENTJOB_DLQ_NAME: "sqs_queue_name"
    sqs-prison-visits-allocation-prisoner-retry-queue-secret:
      HMPPS_SQS_QUEUES_PRISONVISITSALLOCATIONPRISONERRETRYQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-prison-visits-allocation-prisoner-retry-dlq-secret:
      HMPPS_SQS_QUEUES_PRISONVISITSALLOCATIONPRISONERRETRYQUEUE_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

  retryDlqCronjob:
    enabled: true
    retryDlqSchedule: "*/15 * * * *" # Override to every 15 minutes for the DLQ retry. Allows for downstream API issues to resolve before retrying.

generic-prometheus-alerts:
  targetApplication: hmpps-visit-allocation-api

cron:
  visitOrderAllocationJob: "0 1 * * *" # 1 AM every day
