version: "3"
services:
  visit-allocation-db:
    image: postgres:15.7
    networks:
      - hmpps
    container_name: visit-allocation-db
    restart: always
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_PASSWORD=visit_allocation
      - POSTGRES_USER=visit_allocation
      - POSTGRES_DB=visit_allocation
networks:
  hmpps:
