version: "3"
services:
  visit-allocation-db:
    image: postgres:18.0
    networks:
      - hmpps
    container_name: visit-allocation-db
    restart: always
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_PASSWORD=visit_allocation
      - POSTGRES_USER=visit_allocation
      - POSTGRES_DB=visit_allocation

  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    container_name: localstack-hmpps-visit-allocation-alerts
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
networks:
  hmpps:
