apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-visit-allocation-api-allocate-visit-orders-job
spec:
  schedule: "{{ .Values.cron.visitOrderAllocationJob }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 6000
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: allocate-visit-orders-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - |
                  response=$(curl --fail -s -o /dev/null -w "%{http_code}" -XPOST http://hmpps-visit-allocation-api/visits/allocation/job/start)
                  if [ "$response" -ge 200 ] && [ "$response" -lt 300 ]; then
                    echo "Job succeeded with HTTP $response"
                    exit 0
                  else
                    echo "Job failed with HTTP $response"
                    exit 1
                  fi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never
