apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-visit-allocation-api-allocate-visits-job
spec:
  schedule: "{{ .Values.cron.visitAllocationJob }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 6000
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: allocate-visits
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl -XPOST http://hmpps-visit-allocation-api/visits/allocation/job/start
          restartPolicy: Never
