apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-visit-allocation-api-allocate-visit-orders-job
spec:
  schedule: "{{ .Values.cron.visitOrderAllocationJob }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 6000
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: allocate-visit-orders-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - |
                  response=$(curl --fail -s -w "\n%{http_code}" -XPOST http://hmpps-visit-allocation-api/visits/allocation/job/start)
                  body=$(echo "$response" | sed '$d')
                  http_code=$(echo "$response" | tail -n1)

                  if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
                    echo "Job succeeded with HTTP $http_code"
                    echo "Response body:"
                    echo "$body"
                    exit 0
                  else
                    echo "Job failed with HTTP $http_code"
                    echo "Response body:"
                    echo "$body"
                    exit 1
                  fi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never
