apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-visit-allocation-api-allocate-visit-orders-job
spec:
  schedule: "{{ .Values.cron.visitOrderAllocationJob }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 6000
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: allocate-visit-orders-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl -XPOST http://hmpps-visit-allocation-api/visits/allocation/job/start
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never