---
# Per environment values which override defaults in hmpps-visit-allocation-api/values.yaml

generic-service:
  ingress:
    host: hmpps-visit-allocation-api.prison.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISONER_SEARCH_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    INCENTIVES_API_URL: "https://incentives-api.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: visits-alerts
  sqsAlertsQueueNames:
    - "book-a-prison-visit-prod-hmpps_prison_visits_allocation_events_queue"
    - "book-a-prison-visit-prod-hmpps_prison_visits_allocation_events_dlq"
    - "book-a-prison-visit-prod-hmpps_prison_visits_allocation_processing_job_queue"
    - "book-a-prison-visit-prod-hmpps_prison_visits_allocation_processing_job_dlq"
  sqsAlertsOldestThreshold: 1
  sqsAlertsTotalMessagesThreshold: 1