---
# Per environment values which override defaults in hmpps-visit-allocation-api/values.yaml

generic-service:
  ingress:
    host: hmpps-visit-allocation-api.prison.service.justice.gov.uk

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      visit-allocation-rds:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      visit-allocation-rds-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISONER_SEARCH_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    INCENTIVES_API_URL: "https://incentives-api.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api.prison.service.justice.gov.uk"
    VISIT-SCHEDULER_API_URL: "https://visit-scheduler.prison.service.justice.gov.uk"
    SQS_DOMAIN_EVENT_PROCESSING_ENABLED: true
    FEATURE_EVENTS_SNS_ENABLED: true

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: visits-alerts
  sqsAlertsQueueNames:
    - "book-a-prison-visit-prod-hmpps_prison_visits_allocation_events_queue"
    - "book-a-prison-visit-prod-hmpps_prison_visits_allocation_events_dlq"
    - "book-a-prison-visit-prod-hmpps_prison_visits_allocation_processing_job_queue"
    - "book-a-prison-visit-prod-hmpps_prison_visits_allocation_processing_job_dlq"
    - "book-a-prison-visit-prod-hmpps_prison_visits_allocation_prisoner_retry_queue"
    - "book-a-prison-visit-prod-hmpps_prison_visits_allocation_prisoner_retry_dlq"
  sqsAlertsOldestThreshold: 1
  sqsAlertsTotalMessagesThreshold: 1
