---
# Per environment values which override defaults in hmpps-visit-allocation-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-visit-allocation-api-staging.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    PRISONER_SEARCH_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    INCENTIVES_API_URL: "https://incentives-api-dev.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    VISIT-SCHEDULER_API_URL: "https://visit-scheduler-staging.prison.service.justice.gov.uk"
    SQS_DOMAIN_EVENT_PROCESSING_ENABLED: true
    FEATURE_EVENTS_SNS_ENABLED: false # A lot of DPS services don't have staging. Disabling.

  scheduledDowntime:
    enabled: true
    retryDlqSchedule: '*/10 7-20 * * 1-5' # Every 10 minutes 7:00am - 8:50pm UTC Monday-Friday

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: visits-alerts-nonprod
  sqsAlertsQueueNames:
    - "book-a-prison-visit-staging-hmpps_prison_visits_allocation_events_queue"
    - "book-a-prison-visit-staging-hmpps_prison_visits_allocation_events_dlq"
    - "book-a-prison-visit-staging-hmpps_prison_visits_allocation_processing_job_queue"
    - "book-a-prison-visit-staging-hmpps_prison_visits_allocation_processing_job_dlq"
  sqsAlertsOldestThreshold: 1
  sqsAlertsTotalMessagesThreshold: 1

cron:
  visitOrderAllocationJob: "30 9 * * 1-5" # 09:30 AM, Monday to Friday (excluding weekends as our dev envs shut down).
