---
# Per environment values which override defaults in hmpps-visit-allocation-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-visit-allocation-api-preprod.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: visits-alerts-nonprod
  sqsAlertsQueueNames:
    - "book-a-prison-visit-preprod-hmpps_prison_visits_allocation_events_queue"
    - "book-a-prison-visit-preprod-hmpps_prison_visits_allocation_events_dlq"
  sqsAlertsOldestThreshold: 1
  sqsAlertsTotalMessagesThreshold: 1