name: Setup PostgreSQL and Validate Kotlin

on:
  workflow_call:

jobs:
  setup_postgresql_and_validate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.7
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_USER: visit_allocation
          POSTGRES_PASSWORD: visit_allocation
          POSTGRES_DB: visit_allocation
        ports:
          - 5445:5432
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up PostgreSQL database and wait for it to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until docker exec ${GITHUB_JOB} pg_isready -U postgres; do
            sleep 5
          done
          echo "PostgreSQL is up and running!"

      - name: Run Kotlin Validate Workflow
        uses: ministryofjustice/hmpps-github-actions/.github/workflows/kotlin_validate.yml@v2
        with:
          secrets: inherit
