name: Setup Database

on:
  workflow_call:
    inputs:
      postgres_user:
        description: 'PostgreSQL username'
        required: true
        type: string
        default: 'test_user'
      postgres_password:
        description: 'PostgreSQL password'
        required: true
        type: string
        default: 'test_password'
      postgres_db:
        description: 'PostgreSQL database name'
        required: true
        type: string
        default: 'test_db'

jobs:
  setup-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.7
        ports:
          - 5445:5432
        env:
          POSTGRES_USER: ${{ inputs.postgres_user }}
          POSTGRES_PASSWORD: ${{ inputs.postgres_password }}
          POSTGRES_DB: ${{ inputs.postgres_db }}
        options: >-
          --health-cmd="pg_isready -U ${{ inputs.postgres_user }} -d ${{ inputs.postgres_db }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    outputs:
      db_url: ${{ inputs.postgres_user }}:${{ inputs.postgres_password }}@localhost:5432/${{ inputs.postgres_db }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify PostgreSQL is Running
        run: |
          until pg_isready -h localhost -U ${{ inputs.postgres_user }} -d ${{ inputs.postgres_db }};
